// packages/i18n/src/adapters/react/components/I18nText.tsx
/**
 * I18nText component for React
 */

import React from 'react';
import { useI18n } from '../hooks/useI18n';
import type { MessageKey, InterpolationParams } from '../../../types';

export interface I18nTextProps {
  keypath: MessageKey;
  params?: InterpolationParams;
  tag?: keyof JSX.IntrinsicElements;
  locale?: string;
  defaultValue?: string;
  className?: string;
}

export function I18nText({ 
  keypath, 
  params, 
  tag = 'span',
  locale,
  defaultValue,
  className
}: I18nTextProps) {
  const { t } = useI18n();
  
  const translated = t(keypath, {
    params,
    locale,
    defaultValue
  });
  
  const Tag = tag;
  
  return <Tag className={className}>{translated}</Tag>;
}

// packages/i18n/src/adapters/vue/components/I18nText.vue
<template>
  <component :is="tag">
    {{ translatedText }}
  </component>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from '../composables/useI18n';
import type { MessageKey, InterpolationParams } from '../../../types';

interface Props {
  keypath: MessageKey;
  tag?: string;
  params?: InterpolationParams;
  locale?: string;
  plural?: number;
  defaultValue?: string;
}

const props = withDefaults(defineProps<Props>(), {
  tag: 'span'
});

const { t, tc } = useI18n();

const translatedText = computed(() => {
  const options = {
    params: props.params,
    locale: props.locale,
    defaultValue: props.defaultValue
  };
  
  if (props.plural !== undefined) {
    return tc(props.keypath, props.plural, props.params);
  }
  
  return t(props.keypath, options);
});
</script>
