// packages/qrcode/examples/react-example/src/pages/DataTypeExample.tsx
/**
 * React 数据类型示例
 * 展示 @ldesign/qrcode 支持的各种数据类型
 */

import React, { useState, useRef } from 'react'
import { generateQRCode, type QRCodeResult, type SimpleQRCodeOptions } from '@ldesign/qrcode'

interface DataType {
  id: string
  label: string
  icon: string
  defaultData: string
  description: string
}

const DataTypeExample: React.FC = () => {
  const [selectedType, setSelectedType] = useState<string>('')
  const [currentData, setCurrentData] = useState<string>('')
  const [isLoading, setIsLoading] = useState(false)

  const qrContainer = useRef<HTMLDivElement>(null)

  // 数据类型配置
  const dataTypes: DataType[] = [
    {
      id: 'url',
      label: 'URL链接',
      icon: '🌐',
      defaultData: 'https://www.ldesign.com',
      description: '网站链接、在线资源等'
    },
    {
      id: 'wifi',
      label: 'WiFi网络',
      icon: '📶',
      defaultData: 'WIFI:T:WPA;S:LDesign-Office;P:password123;H:false;',
      description: 'WiFi连接信息'
    },
    {
      id: 'contact',
      label: '联系人',
      icon: '👤',
      defaultData: 'BEGIN:VCARD\nVERSION:3.0\nFN:LDesign Team\nORG:LDesign\nTEL:+86-138-0013-8000\nEMAIL:contact@ldesign.com\nURL:https://www.ldesign.com\nEND:VCARD',
      description: '联系人名片信息'
    },
    {
      id: 'email',
      label: '邮件',
      icon: '📧',
      defaultData: 'mailto:contact@ldesign.com?subject=Hello&body=Hi there!',
      description: '预填写邮件内容'
    },
    {
      id: 'sms',
      label: '短信',
      icon: '💬',
      defaultData: 'sms:+86-138-0013-8000?body=Hello from LDesign!',
      description: '预填写短信内容'
    },
    {
      id: 'phone',
      label: '电话',
      icon: '📞',
      defaultData: 'tel:+86-138-0013-8000',
      description: '电话号码'
    },
    {
      id: 'location',
      label: '地理位置',
      icon: '📍',
      defaultData: 'geo:39.9042,116.4074',
      description: '地理坐标位置'
    },
    {
      id: 'text',
      label: '纯文本',
      icon: '📝',
      defaultData: 'Hello, this is a text message from LDesign!',
      description: '普通文本内容'
    }
  ]

  // 快速示例
  const quickExamples = [
    {
      icon: '🌐',
      title: '官网链接',
      description: 'LDesign官方网站',
      data: 'https://www.ldesign.com'
    },
    {
      icon: '📶',
      title: 'WiFi连接',
      description: '办公室WiFi信息',
      data: 'WIFI:T:WPA;S:LDesign-Office;P:***'
    },
    {
      icon: '👤',
      title: '联系名片',
      description: 'LDesign团队联系方式',
      data: 'BEGIN:VCARD...'
    },
    {
      icon: '📧',
      title: '发送邮件',
      description: '预填写邮件内容',
      data: 'mailto:contact@ldesign.com'
    },
    {
      icon: '📍',
      title: '地理位置',
      description: 'LDesign总部位置',
      data: 'geo:39.9042,116.4074'
    }
  ]

  /**
   * 选择数据类型
   */
  const selectDataType = (type: DataType): void => {
    setSelectedType(type.id)
    setCurrentData(type.defaultData)
  }

  /**
   * 生成二维码
   */
  const generateQRCodeHandler = async (): Promise<void> => {
    if (!currentData.trim()) return

    setIsLoading(true)
    try {
      const options: SimpleQRCodeOptions = {
        size: 250,
        format: 'canvas',
        errorCorrectionLevel: 'M'
      }

      const qrResult = await generateQRCode(currentData, options)

      if (qrContainer.current && qrResult.element) {
        qrContainer.current.innerHTML = ''
        qrContainer.current.appendChild(qrResult.element)
      }
    } catch (err) {
      console.error('生成二维码失败:', err)
    } finally {
      setIsLoading(false)
    }
  }

  /**
   * 复制数据到剪贴板
   */
  const copyData = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(currentData)
      alert('数据已复制到剪贴板')
    } catch (err) {
      console.error('复制失败:', err)
    }
  }

  /**
   * 加载快速示例
   */
  const loadExample = (data: string): void => {
    setCurrentData(data)
    setSelectedType('')
  }

  return (
    <div className="datatype-example">
      <h2 className="section-title">数据类型示例</h2>
      <p className="section-description">
        展示 @ldesign/qrcode 支持的各种数据类型，包括URL、WiFi、联系人、地理位置、邮件等。
      </p>

      <div className="grid grid-2">
        {/* 数据类型选择 */}
        <div className="card">
          <h3 className="card-title">数据类型</h3>
          
          <div className="datatype-grid">
            {dataTypes.map((type) => (
              <button
                key={type.id}
                onClick={() => selectDataType(type)}
                className={`datatype-btn ${selectedType === type.id ? 'active' : ''}`}
              >
                <div className="datatype-icon">{type.icon}</div>
                <div className="datatype-label">{type.label}</div>
              </button>
            ))}
          </div>

          {selectedType && (
            <div className="selected-type-info">
              <h4 className="subsection-title">
                {dataTypes.find(t => t.id === selectedType)?.label}
              </h4>
              <p className="type-description">
                {dataTypes.find(t => t.id === selectedType)?.description}
              </p>
            </div>
          )}

          <div className="form-group">
            <label className="form-label">数据内容</label>
            <textarea
              value={currentData}
              onChange={(e) => setCurrentData(e.target.value)}
              className="form-input form-textarea"
              placeholder="请选择数据类型或直接输入内容..."
              rows={6}
            />
          </div>

          <div className="form-actions">
            <button 
              onClick={generateQRCodeHandler} 
              className="btn btn-primary" 
              disabled={!currentData.trim() || isLoading}
            >
              生成二维码
            </button>
            <button 
              onClick={copyData} 
              className="btn" 
              disabled={!currentData.trim()}
            >
              复制数据
            </button>
          </div>
        </div>

        {/* 二维码预览 */}
        <div className="card">
          <h3 className="card-title">二维码预览</h3>
          
          <div className="qr-preview">
            {isLoading && (
              <div className="loading">
                <div className="loading-spinner"></div>
                <p>正在生成二维码...</p>
              </div>
            )}
            
            {!isLoading && currentData && (
              <div className="qr-container" ref={qrContainer}></div>
            )}
            
            {!currentData && !isLoading && (
              <div className="placeholder">
                <div className="placeholder-icon">📱</div>
                <p>选择数据类型并填写信息</p>
              </div>
            )}
          </div>

          {currentData && (
            <div className="data-preview">
              <h4 className="subsection-title">数据预览</h4>
              <pre className="data-content">{currentData}</pre>
            </div>
          )}
        </div>
      </div>

      {/* 快速示例 */}
      <div className="card">
        <h3 className="card-title">快速示例</h3>
        <div className="quick-examples-grid">
          {quickExamples.map((example, index) => (
            <div
              key={index}
              onClick={() => loadExample(example.data)}
              className="example-card"
            >
              <div className="example-icon">{example.icon}</div>
              <h4 className="example-title">{example.title}</h4>
              <p className="example-description">{example.description}</p>
              <div className="example-data">{example.data}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default DataTypeExample

// packages/qrcode/examples/vue3-example/src/views/DataTypeExample.vue
<template>
  <div class="datatype-example">
    <h2 class="section-title">数据类型示例</h2>
    <p class="section-description">
      展示 @ldesign/qrcode 支持的各种数据类型，包括URL、WiFi、联系人、地理位置、邮件等。
    </p>

    <div class="grid grid-2">
      <!-- 数据类型选择 -->
      <div class="card">
        <h3 class="card-title">数据类型</h3>
        
        <div class="type-selector">
          <button
            v-for="type in dataTypes"
            :key="type.id"
            :class="['type-btn', { active: activeType === type.id }]"
            @click="selectType(type)"
          >
            <span class="type-icon">{{ type.icon }}</span>
            <span class="type-label">{{ type.label }}</span>
          </button>
        </div>

        <!-- 动态表单 -->
        <div class="data-form">
          <component
            :is="currentFormComponent"
            v-model="formData"
            @update="generateQRCode"
          />
        </div>

        <div class="form-actions">
          <button @click="generateQRCode" class="btn btn-primary" :disabled="!isFormValid">
            生成二维码
          </button>
          <button @click="copyToClipboard" class="btn" :disabled="!currentData">
            复制数据
          </button>
        </div>
      </div>

      <!-- 预览面板 -->
      <div class="card">
        <h3 class="card-title">二维码预览</h3>
        
        <div class="preview-area">
          <div v-if="isLoading" class="loading">
            <div class="loading-spinner"></div>
            <p>正在生成二维码...</p>
          </div>
          
          <div v-else-if="result" class="qr-result">
            <div class="qr-container" ref="qrContainer"></div>
            <div class="qr-info">
              <h4>数据信息</h4>
              <p><strong>类型:</strong> {{ activeTypeInfo?.label }}</p>
              <p><strong>格式:</strong> {{ result.format }}</p>
              <p><strong>大小:</strong> {{ result.size }}px</p>
              <div class="data-preview">
                <h5>编码数据:</h5>
                <pre>{{ currentData }}</pre>
              </div>
            </div>
          </div>
          
          <div v-else class="placeholder">
            <div class="placeholder-icon">📱</div>
            <p>选择数据类型并填写信息</p>
          </div>
        </div>
      </div>
    </div>

    <!-- 快速示例 -->
    <div class="card">
      <h3 class="card-title">快速示例</h3>
      <div class="quick-examples">
        <div
          v-for="example in quickExamples"
          :key="example.label"
          class="example-card"
          @click="loadExample(example)"
        >
          <div class="example-icon">{{ example.icon }}</div>
          <h4>{{ example.label }}</h4>
          <p>{{ example.description }}</p>
          <div class="example-preview">{{ example.preview }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick } from 'vue'
import {
  generateQRCode,
  type QRCodeResult,
  type SimpleQRCodeOptions
} from '@ldesign/qrcode'

// 数据类型定义
const dataTypes = [
  { id: 'url', label: 'URL链接', icon: '🌐' },
  { id: 'wifi', label: 'WiFi网络', icon: '📶' },
  { id: 'contact', label: '联系人', icon: '👤' },
  { id: 'email', label: '邮件', icon: '📧' },
  { id: 'sms', label: '短信', icon: '💬' },
  { id: 'phone', label: '电话', icon: '📞' },
  { id: 'location', label: '地理位置', icon: '📍' },
  { id: 'text', label: '纯文本', icon: '📝' }
]

// 响应式数据
const activeType = ref('url')
const formData = ref<any>({})
const isLoading = ref(false)
const result = ref<QRCodeResult | null>(null)
const qrContainer = ref<HTMLDivElement>()

// 计算属性
const activeTypeInfo = computed(() => 
  dataTypes.find(type => type.id === activeType.value)
)

const currentFormComponent = computed(() => {
  const componentMap: Record<string, string> = {
    url: 'URLForm',
    wifi: 'WiFiForm',
    contact: 'ContactForm',
    email: 'EmailForm',
    sms: 'SMSForm',
    phone: 'PhoneForm',
    location: 'LocationForm',
    text: 'TextForm'
  }
  return componentMap[activeType.value] || 'TextForm'
})

const isFormValid = computed(() => {
  switch (activeType.value) {
    case 'url':
      return formData.value.url?.trim()
    case 'wifi':
      return formData.value.ssid?.trim()
    case 'contact':
      return formData.value.name?.trim()
    case 'email':
      return formData.value.email?.trim()
    case 'sms':
      return formData.value.phone?.trim()
    case 'phone':
      return formData.value.phone?.trim()
    case 'location':
      return formData.value.latitude && formData.value.longitude
    case 'text':
      return formData.value.text?.trim()
    default:
      return false
  }
})

const currentData = computed(() => {
  switch (activeType.value) {
    case 'url':
      return formData.value.url || ''
    case 'wifi':
      return `WIFI:T:${formData.value.security || 'WPA'};S:${formData.value.ssid || ''};P:${formData.value.password || ''};H:${formData.value.hidden ? 'true' : 'false'};;`
    case 'contact':
      return `BEGIN:VCARD\nVERSION:3.0\nFN:${formData.value.name || ''}\nORG:${formData.value.organization || ''}\nTEL:${formData.value.phone || ''}\nEMAIL:${formData.value.email || ''}\nURL:${formData.value.website || ''}\nEND:VCARD`
    case 'email':
      return `mailto:${formData.value.email || ''}?subject=${encodeURIComponent(formData.value.subject || '')}&body=${encodeURIComponent(formData.value.body || '')}`
    case 'sms':
      return `sms:${formData.value.phone || ''}?body=${encodeURIComponent(formData.value.message || '')}`
    case 'phone':
      return `tel:${formData.value.phone || ''}`
    case 'location':
      return `geo:${formData.value.latitude || 0},${formData.value.longitude || 0}`
    case 'text':
      return formData.value.text || ''
    default:
      return ''
  }
})

// 快速示例
const quickExamples = [
  {
    label: '官网链接',
    icon: '🌐',
    description: 'LDesign官方网站',
    preview: 'https://www.ldesign.com',
    type: 'url',
    data: { url: 'https://www.ldesign.com' }
  },
  {
    label: 'WiFi连接',
    icon: '📶',
    description: '办公室WiFi信息',
    preview: 'WIFI:T:WPA;S:LDesign-Office;P:***',
    type: 'wifi',
    data: { ssid: 'LDesign-Office', password: 'ldesign2025', security: 'WPA' }
  },
  {
    label: '联系名片',
    icon: '👤',
    description: 'LDesign团队联系方式',
    preview: 'BEGIN:VCARD...',
    type: 'contact',
    data: {
      name: 'LDesign Team',
      organization: 'LDesign',
      phone: '+86-138-0013-8000',
      email: 'contact@ldesign.com',
      website: 'https://www.ldesign.com'
    }
  },
  {
    label: '发送邮件',
    icon: '📧',
    description: '预填写邮件内容',
    preview: 'mailto:contact@ldesign.com',
    type: 'email',
    data: {
      email: 'contact@ldesign.com',
      subject: '关于LDesign的咨询',
      body: '您好，我想了解更多关于LDesign的信息。'
    }
  },
  {
    label: '地理位置',
    icon: '📍',
    description: 'LDesign总部位置',
    preview: 'geo:39.9042,116.4074',
    type: 'location',
    data: { latitude: 39.9042, longitude: 116.4074 }
  }
]

/**
 * 选择数据类型
 */
const selectType = (type: typeof dataTypes[0]): void => {
  activeType.value = type.id
  formData.value = {}
  result.value = null
}

/**
 * 生成二维码
 */
const generateQRCode = async (): Promise<void> => {
  if (!isFormValid.value) return

  isLoading.value = true

  try {
    const options: SimpleQRCodeOptions = {
      size: 250,
      format: 'canvas',
      errorCorrectionLevel: 'M'
    }

    const qrResult = await generateQRCode(currentData.value, options)
    result.value = qrResult

    await nextTick()
    if (qrContainer.value && qrResult.element) {
      qrContainer.value.innerHTML = ''
      qrContainer.value.appendChild(qrResult.element)
    }
  } catch (error) {
    console.error('生成二维码失败:', error)
  } finally {
    isLoading.value = false
  }
}

/**
 * 复制到剪贴板
 */
const copyToClipboard = async (): Promise<void> => {
  if (!currentData.value) return

  try {
    await navigator.clipboard.writeText(currentData.value)
    console.log('数据已复制到剪贴板')
  } catch (error) {
    console.error('复制失败:', error)
  }
}

/**
 * 加载快速示例
 */
const loadExample = (example: typeof quickExamples[0]): void => {
  activeType.value = example.type
  formData.value = { ...example.data }
  generateQRCode()
}
</script>

<!-- 表单组件定义 -->
<script lang="ts">
import { defineComponent } from 'vue'

// URL表单组件
const URLForm = defineComponent({
  props: ['modelValue'],
  emits: ['update:modelValue', 'update'],
  template: `
    <div>
      <div class="form-group">
        <label class="form-label">网址URL</label>
        <input
          :value="modelValue.url || ''"
          @input="updateValue('url', $event.target.value)"
          type="url"
          class="form-input"
          placeholder="https://www.example.com"
        />
      </div>
    </div>
  `,
  methods: {
    updateValue(key: string, value: any) {
      const newValue = { ...this.modelValue, [key]: value }
      this.$emit('update:modelValue', newValue)
      this.$emit('update')
    }
  }
})

// WiFi表单组件
const WiFiForm = defineComponent({
  props: ['modelValue'],
  emits: ['update:modelValue', 'update'],
  template: `
    <div>
      <div class="form-group">
        <label class="form-label">网络名称(SSID)</label>
        <input
          :value="modelValue.ssid || ''"
          @input="updateValue('ssid', $event.target.value)"
          type="text"
          class="form-input"
          placeholder="WiFi网络名称"
        />
      </div>
      <div class="form-group">
        <label class="form-label">密码</label>
        <input
          :value="modelValue.password || ''"
          @input="updateValue('password', $event.target.value)"
          type="password"
          class="form-input"
          placeholder="WiFi密码"
        />
      </div>
      <div class="form-group">
        <label class="form-label">安全类型</label>
        <select
          :value="modelValue.security || 'WPA'"
          @change="updateValue('security', $event.target.value)"
          class="form-input"
        >
          <option value="WPA">WPA/WPA2</option>
          <option value="WEP">WEP</option>
          <option value="nopass">无密码</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">
          <input
            :checked="modelValue.hidden || false"
            @change="updateValue('hidden', $event.target.checked)"
            type="checkbox"
            class="form-checkbox"
          />
          隐藏网络
        </label>
      </div>
    </div>
  `,
  methods: {
    updateValue(key: string, value: any) {
      const newValue = { ...this.modelValue, [key]: value }
      this.$emit('update:modelValue', newValue)
      this.$emit('update')
    }
  }
})

// 其他表单组件类似定义...
// 为了简化，这里只展示主要的两个组件

export default {
  components: {
    URLForm,
    WiFiForm,
    // 其他组件...
  }
}
</script>

<style scoped>
.datatype-example {
  max-width: 100%;
}

.section-title {
  font-size: 1.8rem;
  font-weight: 600;
  color: var(--ldesign-text-color-primary);
  margin-bottom: var(--ls-spacing-sm);
}

.section-description {
  color: var(--ldesign-text-color-secondary);
  margin-bottom: var(--ls-spacing-lg);
  line-height: 1.6;
}

.card-title {
  font-size: 1.2rem;
  font-weight: 600;
  color: var(--ldesign-text-color-primary);
  margin-bottom: var(--ls-spacing-base);
  padding-bottom: var(--ls-spacing-xs);
  border-bottom: 2px solid var(--ldesign-brand-color-2);
}

.type-selector {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  gap: var(--ls-spacing-xs);
  margin-bottom: var(--ls-spacing-base);
}

.type-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: var(--ls-spacing-sm);
  border: 1px solid var(--ldesign-border-level-2-color);
  border-radius: var(--ls-border-radius-base);
  background: var(--ldesign-bg-color-container);
  cursor: pointer;
  transition: all 0.2s ease;
}

.type-btn:hover {
  background: var(--ldesign-bg-color-container-hover);
  border-color: var(--ldesign-brand-color-6);
}

.type-btn.active {
  background: var(--ldesign-brand-color-1);
  border-color: var(--ldesign-brand-color-6);
  color: var(--ldesign-brand-color-7);
}

.type-icon {
  font-size: 1.5rem;
  margin-bottom: var(--ls-spacing-xs);
}

.type-label {
  font-size: 12px;
  font-weight: 500;
  text-align: center;
}

.data-form {
  background: var(--ldesign-gray-color-1);
  padding: var(--ls-spacing-base);
  border-radius: var(--ls-border-radius-base);
  margin-bottom: var(--ls-spacing-base);
}

.form-actions {
  display: flex;
  gap: var(--ls-spacing-sm);
}

.preview-area {
  min-height: 350px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.loading {
  text-align: center;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 3px solid var(--ldesign-border-level-1-color);
  border-top: 3px solid var(--ldesign-brand-color-6);
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: var(--ls-spacing-sm);
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.qr-result {
  text-align: center;
  width: 100%;
}

.qr-container {
  margin-bottom: var(--ls-spacing-base);
  display: flex;
  justify-content: center;
}

.qr-info {
  background: var(--ldesign-gray-color-1);
  padding: var(--ls-spacing-sm);
  border-radius: var(--ls-border-radius-base);
  text-align: left;
}

.qr-info h4 {
  margin-bottom: var(--ls-spacing-sm);
  color: var(--ldesign-text-color-primary);
}

.qr-info p {
  margin-bottom: var(--ls-spacing-xs);
  font-size: 14px;
}

.data-preview {
  margin-top: var(--ls-spacing-sm);
}

.data-preview h5 {
  margin-bottom: var(--ls-spacing-xs);
  color: var(--ldesign-text-color-primary);
}

.data-preview pre {
  background: white;
  padding: var(--ls-spacing-xs);
  border-radius: var(--ls-border-radius-sm);
  font-size: 12px;
  overflow-x: auto;
  border: 1px solid var(--ldesign-border-level-1-color);
}

.placeholder {
  text-align: center;
  color: var(--ldesign-text-color-placeholder);
}

.placeholder-icon {
  font-size: 3rem;
  margin-bottom: var(--ls-spacing-sm);
}

.quick-examples {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--ls-spacing-base);
}

.example-card {
  padding: var(--ls-spacing-base);
  border: 1px solid var(--ldesign-border-level-1-color);
  border-radius: var(--ls-border-radius-base);
  background: var(--ldesign-bg-color-container);
  cursor: pointer;
  transition: all 0.2s ease;
  text-align: center;
}

.example-card:hover {
  background: var(--ldesign-bg-color-container-hover);
  box-shadow: var(--ldesign-shadow-2);
  transform: translateY(-2px);
}

.example-icon {
  font-size: 2rem;
  margin-bottom: var(--ls-spacing-sm);
}

.example-card h4 {
  margin-bottom: var(--ls-spacing-xs);
  color: var(--ldesign-text-color-primary);
}

.example-card p {
  margin-bottom: var(--ls-spacing-sm);
  color: var(--ldesign-text-color-secondary);
  font-size: 14px;
}

.example-preview {
  background: var(--ldesign-gray-color-1);
  padding: var(--ls-spacing-xs);
  border-radius: var(--ls-border-radius-sm);
  font-size: 12px;
  font-family: monospace;
  color: var(--ldesign-text-color-secondary);
  word-break: break-all;
}

.form-checkbox {
  width: 16px;
  height: 16px;
  margin-right: var(--ls-spacing-xs);
  cursor: pointer;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .type-selector {
    grid-template-columns: repeat(2, 1fr);
  }
  
  .form-actions {
    flex-direction: column;
  }
  
  .quick-examples {
    grid-template-columns: 1fr;
  }
}
</style>
