// library/grid/src/adapters/vue/components/GridDragSource.vue
<template>
  <div
    ref="dragSourceRef"
    class="grid-drag-source"
    :class="{ 'is-dragging': isDragging }"
    draggable="true"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, inject, onMounted, onUnmounted, type Ref } from 'vue'
import type { IGridInstance } from '../../../types'
import type { GridDragSourceProps } from '../types'

const props = withDefaults(defineProps<GridDragSourceProps>(), {
  helper: 'clone',
  revert: false
})

const dragSourceRef = ref<HTMLElement>()
const isDragging = ref(false)
// GridInstance is optional - when used outside GridStack, will drag to any accepting grid
const gridInstance = inject<Ref<IGridInstance> | undefined>('grid-instance', undefined)
let cleanup: (() => void) | undefined

onMounted(() => {
  if (!dragSourceRef.value) return

  const element = dragSourceRef.value

  // If inside a GridStack, register with its drag manager
  if (gridInstance?.value) {
    const dragManager = gridInstance.value.getDragManager()
    
    // Register drag source
    cleanup = dragManager.registerDragSource(element, {
      data: props.data,
      itemOptions: props.itemOptions,
      preview: props.preview,
      helper: props.helper,
      revert: props.revert
    })
  } else {
    // For external drag sources, set data attributes for GridStack to pick up
    if (props.data) {
      element.setAttribute('data-drag-source', JSON.stringify({
        data: props.data,
        itemOptions: props.itemOptions || {}
      }))
    }
  }

  // Add drag event listeners
  const handleDragStart = (e: DragEvent) => {
    isDragging.value = true
    
    // For external drag sources, set drag data
    if (!gridInstance?.value && e.dataTransfer) {
      e.dataTransfer.effectAllowed = 'copy'
      e.dataTransfer.setData('application/json', JSON.stringify({
        data: props.data,
        itemOptions: props.itemOptions || {}
      }))
    }
  }

  const handleDragEnd = () => {
    isDragging.value = false
  }

  element.addEventListener('dragstart', handleDragStart)
  element.addEventListener('dragend', handleDragEnd)

  // Store cleanup for event listeners
  const originalCleanup = cleanup
  cleanup = () => {
    originalCleanup?.()
    element.removeEventListener('dragstart', handleDragStart)
    element.removeEventListener('dragend', handleDragEnd)
  }
})

onUnmounted(() => {
  cleanup?.()
})

defineExpose({
  dragSourceRef,
  isDragging
})
</script>

<style>
.grid-drag-source {
  cursor: move;
  user-select: none;
}

.grid-drag-source.is-dragging {
  opacity: 0.5;
}

.grid-drag-source:hover {
  background-color: rgba(0, 0, 0, 0.05);
}
</style>

// library/grid/src/adapters/react/components/GridDragSource.tsx
/**
 * React GridDragSource component
 */

import React, { useRef, useEffect, useState, useContext } from 'react'
import type { GridDragSourceProps } from '../types'
import { GridContext } from '../context/GridContext'

export const GridDragSource: React.FC<GridDragSourceProps> = (props) => {
  const {
    data,
    itemOptions,
    preview,
    helper = 'clone',
    revert = false,
    children,
    className = '',
    style
  } = props

  const dragSourceRef = useRef<HTMLDivElement>(null)
  const [isDragging, setIsDragging] = useState(false)
  const { gridInstance } = useContext(GridContext)

  useEffect(() => {
    if (!dragSourceRef.current || !gridInstance) return

    const dragManager = gridInstance.getDragManager()
    const element = dragSourceRef.current

    // Register drag source
    const cleanup = dragManager.registerDragSource(element, {
      data,
      itemOptions,
      preview,
      helper,
      revert
    })

    // Add drag event listeners
    const handleDragStart = () => {
      setIsDragging(true)
    }

    const handleDragEnd = () => {
      setIsDragging(false)
    }

    element.addEventListener('dragstart', handleDragStart)
    element.addEventListener('dragend', handleDragEnd)

    return () => {
      cleanup()
      element.removeEventListener('dragstart', handleDragStart)
      element.removeEventListener('dragend', handleDragEnd)
    }
  }, [gridInstance, data, itemOptions, preview, helper, revert])

  return (
    <div
      ref={dragSourceRef}
      className={`grid-drag-source ${isDragging ? 'is-dragging' : ''} ${className}`}
      style={{
        cursor: 'move',
        userSelect: 'none',
        ...style
      }}
      draggable
    >
      {children}
    </div>
  )
}

GridDragSource.displayName = 'GridDragSource'

export default GridDragSource
