// packages/color/src/react/ThemePicker.tsx
import React, { useState, useRef, useEffect, useMemo } from 'react'
import { useTheme } from './useTheme'
import { PresetTheme } from '../themes/presets'
import './ThemePicker.css'

export interface ThemePickerProps {
  value?: string
  onChange?: (value: string, preset?: PresetTheme) => void
  showArrow?: boolean
  showSearch?: boolean
  showCustom?: boolean
  prefix?: string
  storageKey?: string
}

export const ThemePicker: React.FC<ThemePickerProps> = ({
  value,
  onChange,
  showArrow = true,
  showSearch = false,
  showCustom = false,
  prefix = 'ld',
  storageKey
}) => {
  const pickerRef = useRef<HTMLDivElement>(null)
  const [isOpen, setIsOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [customColor, setCustomColor] = useState('#1890ff')
  const [dropdownStyle, setDropdownStyle] = useState<React.CSSProperties>({})

  const {
    currentTheme,
    presets,
    primaryColor,
    themeName,
    applyTheme,
    applyPresetTheme,
    restoreTheme
  } = useTheme({
    prefix,
    storageKey
  })

  // Current color
  const currentColor = useMemo(() => {
    return value || primaryColor || '#1890ff'
  }, [value, primaryColor])

  // Current label
  const currentLabel = useMemo(() => {
    const preset = presets.find(p => p.name === themeName)
    return preset?.label || '主题色'
  }, [presets, themeName])

// Build visible presets (prepend current custom color if not in presets)
  const visiblePresets = useMemo(() => {
    const list: PresetTheme[] = [...presets]
    const inPresets = list.some(p => p.color.toLowerCase() === (currentColor || '').toLowerCase())
    if (!inPresets) {
      list.unshift({ name: 'custom', label: '自定义', color: currentColor, custom: true })
    }
    return list
  }, [presets, currentColor])

  // Filtered presets (if search enabled)
  const filteredPresets = useMemo(() => {
    if (!searchQuery) return visiblePresets
    const query = searchQuery.toLowerCase()
    return visiblePresets.filter(preset =>
      preset.label.toLowerCase().includes(query) ||
      preset.name.toLowerCase().includes(query) ||
      preset.color.toLowerCase().includes(query)
    )
  }, [visiblePresets, searchQuery])

  // Toggle dropdown
  const toggleDropdown = () => {
    setIsOpen(!isOpen)
    if (!isOpen) {
      updateDropdownPosition()
    }
  }

// Update dropdown position (prevent overflow on small screens)
  const updateDropdownPosition = () => {
    if (!pickerRef.current) return

    const rect = pickerRef.current.getBoundingClientRect()
    const dropdownHeight = 400
    const viewportWidth = window.innerWidth
    const viewportHeight = window.innerHeight
    const desiredWidth = Math.min(320, Math.max(240, viewportWidth - 16))

    const spaceBelow = viewportHeight - rect.bottom
    const spaceAbove = rect.top

    let top = rect.bottom + 4
    if (spaceBelow < dropdownHeight && spaceAbove > spaceBelow) {
      top = rect.top - dropdownHeight - 4
    }
    // Clamp within viewport with 8px margin
    top = Math.max(8, Math.min(top, viewportHeight - 8 - dropdownHeight))

    let left = rect.left
    const maxLeft = viewportWidth - 8 - desiredWidth
    left = Math.max(8, Math.min(left, Math.max(8, maxLeft)))

    setDropdownStyle({
      position: 'fixed',
      top: `${top}px`,
      left: `${left}px`,
      width: `${desiredWidth}px`,
      zIndex: 9999
    })
  }

  // Select preset
  const selectPreset = (preset: PresetTheme) => {
    applyPresetTheme(preset.name)
    onChange?.(preset.color, preset)
    setIsOpen(false)
  }

  // Handle custom color
  const handleCustomColor = () => {
    if (customColor) {
      applyTheme(customColor)
      onChange?.(customColor)
      setIsOpen(false)
    }
  }

  // Handle click outside
  const handleClickOutside = (event: MouseEvent) => {
    if (!pickerRef.current?.contains(event.target as Node)) {
      setIsOpen(false)
    }
  }

  // Handle resize
  const handleResize = () => {
    if (isOpen) {
      updateDropdownPosition()
    }
  }

  useEffect(() => {
    // Restore theme on mount
    restoreTheme()

    // Add event listeners
    document.addEventListener('click', handleClickOutside)
    window.addEventListener('resize', handleResize)
    window.addEventListener('scroll', handleResize)

    return () => {
      document.removeEventListener('click', handleClickOutside)
      window.removeEventListener('resize', handleResize)
      window.removeEventListener('scroll', handleResize)
    }
  }, [])

  // Watch value changes
  useEffect(() => {
    if (value && value !== primaryColor) {
      applyTheme(value)
    }
  }, [value, primaryColor, applyTheme])

  return (
    <div className="ld-theme-picker" ref={pickerRef}>
      <button
        className="ld-theme-picker__trigger"
        onClick={toggleDropdown}
        style={{ backgroundColor: currentColor }}
        title={currentLabel}
      >
        <span 
          className="ld-theme-picker__color" 
          style={{ backgroundColor: currentColor }}
        />
        {showArrow && (
          <svg 
            className={`ld-theme-picker__arrow ${isOpen ? 'is-open' : ''}`}
            width="12" 
            height="12" 
            viewBox="0 0 12 12"
          >
            <path 
              d="M2.5 4.5L6 8L9.5 4.5" 
              stroke="currentColor" 
              strokeWidth="1.5" 
              fill="none"
            />
          </svg>
        )}
      </button>

      {isOpen && (
        <div
          className="ld-theme-picker__dropdown"
          style={dropdownStyle}
          onClick={(e) => e.stopPropagation()}
        >
          {showSearch && (
            <div className="ld-theme-picker__search">
              <input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                type="text"
                placeholder="搜索颜色..."
                className="ld-theme-picker__search-input"
              />
            </div>
          )}

          <div className="ld-theme-picker__content">
            {showCustom && (
              <div className="ld-theme-picker__custom">
                <label className="ld-theme-picker__label">自定义颜色</label>
                <div className="ld-theme-picker__custom-input">
                  <input
                    value={customColor}
                    onChange={(e) => setCustomColor(e.target.value)}
                    type="color"
                    className="ld-theme-picker__color-input"
                  />
                  <input
                    value={customColor}
                    onChange={(e) => setCustomColor(e.target.value)}
                    onKeyUp={(e) => e.key === 'Enter' && handleCustomColor()}
                    type="text"
                    placeholder="#000000"
                    className="ld-theme-picker__hex-input"
                  />
                  <button
                    className="ld-theme-picker__apply-btn"
                    onClick={handleCustomColor}
                  >
                    应用
                  </button>
                </div>
              </div>
            )}

<div className="ld-theme-picker__presets">
              <label className="ld-theme-picker__label">选择主题色</label>
              <div className="ld-theme-picker__grid">
                {filteredPresets.map((preset) => (
                  <div
                    key={`${preset.name}-${preset.color}`}
                    className={`ld-theme-picker__preset ${
                      (preset.name === themeName) || (!themeName && preset.custom) ? 'is-active' : ''
                    }`}
                    onClick={() => selectPreset(preset)}
                  >
                    <span
                      className="ld-theme-picker__preset-color"
                      style={{ backgroundColor: preset.color }}
                      title={preset.label}
                    >
                      {((preset.name === themeName) || (!themeName && preset.custom)) && (
                        <svg 
                          className="ld-theme-picker__check" 
                          width="16" 
                          height="16" 
                          viewBox="0 0 16 16"
                        >
                          <path 
                            d="M3 8L6 11L13 4" 
                            stroke="white" 
                            strokeWidth="2" 
                            fill="none"
                          />
                        </svg>
                      )}
                    </span>
                    <span className="ld-theme-picker__preset-label">
                      {preset.custom ? '自定义' : preset.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// packages/color/src/vue/ThemePicker.vue
<template>
  <div class="ld-theme-picker" ref="pickerRef">
    <button 
      class="ld-theme-picker__trigger"
      @click="toggleDropdown"
      :title="currentLabel"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" :stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="13.5" cy="6.5" r=".5" :fill="currentColor"/>
        <circle cx="17.5" cy="10.5" r=".5" :fill="currentColor"/>
        <circle cx="8.5" cy="7.5" r=".5" :fill="currentColor"/>
        <circle cx="6.5" cy="12.5" r=".5" :fill="currentColor"/>
        <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/>
      </svg>
    </button>
    
    <Teleport to="body">
      <Transition name="ld-theme-picker-fade">
        <div 
          v-if="isOpen"
          class="ld-theme-picker__dropdown"
          :style="dropdownStyle"
          @click.stop
        >
        <div v-if="showSearch" class="ld-theme-picker__search">
          <input 
            v-model="searchQuery"
            type="text"
            :placeholder="t('theme.searchPlaceholder', 'Search colors...')"
            class="ld-theme-picker__search-input"
          />
        </div>
        
        <div class="ld-theme-picker__content">
          <div v-if="showCustom" class="ld-theme-picker__custom">
            <label class="ld-theme-picker__label">{{ t('theme.customColor', 'Custom Color') }}</label>
            <div class="ld-theme-picker__custom-input">
              <input 
                v-model="customColor"
                type="color"
                class="ld-theme-picker__color-input"
                @change="handleCustomColor"
              />
              <input 
                v-model="customColor"
                type="text"
                placeholder="#000000"
                class="ld-theme-picker__hex-input"
                @keyup.enter="handleCustomColor"
              />
              <button 
                class="ld-theme-picker__apply-btn"
                @click="handleCustomColor"
              >
                {{ t('theme.apply', 'Apply') }}
              </button>
            </div>

            <!-- 添加自定义主题 -->
            <div class="ld-theme-picker__add-theme" v-if="showAddCustomTheme">
              <label class="ld-theme-picker__label">{{ t('theme.addCustomTheme', 'Add Custom Theme') }}</label>
              <div class="ld-theme-picker__add-input">
                <input 
                  v-model="newThemeName"
                  type="text"
                  :placeholder="t('theme.themeName', 'Theme name')"
                  class="ld-theme-picker__name-input"
                />
                <input 
                  v-model="newThemeColor"
                  type="color"
                  class="ld-theme-picker__color-input"
                />
                <input 
                  v-model="newThemeColor"
                  type="text"
                  placeholder="#000000"
                  class="ld-theme-picker__hex-input"
                />
                <button 
                  class="ld-theme-picker__add-btn"
                  @click="handleAddCustomTheme"
                  :disabled="!newThemeName || !newThemeColor"
                >
                  {{ t('theme.add', 'Add') }}
                </button>
              </div>
            </div>
          </div>
          
          <div class="ld-theme-picker__presets">
            <label class="ld-theme-picker__label">{{ t('theme.selectThemeColor', '选择主题色') }}</label>
            <div class="ld-theme-picker__grid">
              <div
                v-for="preset in filteredPresets"
                :key="`${preset.name}-${preset.color}`"
                class="ld-theme-picker__preset"
                :class="{ 'is-active': (preset.name === themeName) || (!themeName && preset.custom), 'is-custom': preset.custom }"
              >
                <span 
                  class="ld-theme-picker__preset-color"
                  :style="{ backgroundColor: preset.color }"
                  :title="preset.label"
                  @click="selectPreset(preset)"
                >
                  <svg v-if="(preset.name === themeName) || (!themeName && preset.custom)" class="ld-theme-picker__check" width="16" height="16" viewBox="0 0 16 16">
                    <path d="M3 8L6 11L13 4" stroke="white" stroke-width="2" fill="none"/>
                  </svg>
                </span>
                <span 
                  class="ld-theme-picker__preset-label"
                  @click="selectPreset(preset)"
                >{{ preset.custom ? '自定义' : t(`theme.presets.${preset.name}`, preset.label) }}</span>
                <!-- 删除按钮（仅自定义主题） -->
                <button
                  v-if="preset.custom && showRemoveButton"
                  class="ld-theme-picker__remove-btn"
                  @click.stop="handleRemoveCustomTheme(preset.name)"
                  :title="t('theme.remove', 'Remove')"
                >
                  ×
                </button>
              </div>
            </div>
          </div>
        </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, nextTick, getCurrentInstance } from 'vue'
import { useTheme } from './useTheme'
import type { PresetTheme } from '../themes/presets'

interface Props {
  modelValue?: string
  showArrow?: boolean
  showSearch?: boolean
  showCustom?: boolean
  showAddCustomTheme?: boolean
  showRemoveButton?: boolean
  prefix?: string
  storageKey?: string
}

const props = withDefaults(defineProps<Props>(), {
  showArrow: true,
  showSearch: false,
  showCustom: false,
  showAddCustomTheme: false,
  showRemoveButton: true,
  prefix: 'ld'
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'change': [value: string, preset?: PresetTheme]
}>()

// Optional i18n support
const instance = getCurrentInstance()
const i18n = instance?.appContext.config.globalProperties.$i18n
const t = (key: string, fallback?: string) => {
  if (i18n && typeof i18n.t === 'function') {
    return i18n.t(key)
  }
  return fallback || key
}

const pickerRef = ref<HTMLElement>()
const isOpen = ref(false)
const searchQuery = ref('')
const customColor = ref('#1890ff')
const newThemeName = ref('')
const newThemeColor = ref('#1890ff')
const dropdownStyle = ref({})

const { 
  currentTheme,
  presets,
  primaryColor,
  themeName,
  applyTheme,
  applyPresetTheme,
  restoreTheme
} = useTheme({
  prefix: props.prefix,
  storageKey: props.storageKey
})

// 当前颜色
const currentColor = computed(() => {
  return props.modelValue || primaryColor.value || '#1890ff'
})

// 当前标签
const currentLabel = computed(() => {
  const preset = presets.value.find(p => p.name === themeName.value)
  if (preset) {
    // Use i18n for preset labels
    const i18nKey = `theme.presets.${preset.name}`
    return t(i18nKey, preset.label)
  }
  return t('theme.title', '主题色')
})

// Build visible presets (prepend current custom color if not in presets)
const visiblePresets = computed(() => {
  const list: PresetTheme[] = [...presets.value]
  const inPresets = list.some(p => p.color.toLowerCase() === (currentColor.value || '').toLowerCase())
  if (!inPresets) {
    list.unshift({ name: 'custom', label: '自定义', color: currentColor.value, custom: true })
  }
  return list
})

// 过滤的预设（按 order 排序）
const filteredPresets = computed(() => {
  let filtered = visiblePresets.value
  
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()
    filtered = filtered.filter(preset => 
      preset.label.toLowerCase().includes(query) ||
      preset.name.toLowerCase().includes(query) ||
      preset.color.toLowerCase().includes(query)
    )
  }
  
  // 按 order 排序
  return [...filtered].sort((a, b) => {
    const orderA = a.order ?? 9999
    const orderB = b.order ?? 9999
    return orderA - orderB
  })
})

// 切换下拉框
const toggleDropdown = () => {
  isOpen.value = !isOpen.value
  if (isOpen.value) {
    nextTick(() => updateDropdownPosition())
  }
}

// 更新下拉框位置（防止溢出屏幕，优先正下方）
const updateDropdownPosition = () => {
  if (!pickerRef.value) return
  
  const rect = pickerRef.value.getBoundingClientRect()
  const dropdownHeight = 360
  const viewportWidth = window.innerWidth
  const viewportHeight = window.innerHeight
  const desiredWidth = 296
  const margin = 16
  
  const spaceBelow = viewportHeight - rect.bottom - margin
  const spaceAbove = rect.top - margin
  
  // 优先正下方，空间不足时考虑上方
  let top = rect.bottom + margin
  if (spaceBelow < dropdownHeight && spaceAbove > spaceBelow) {
    top = rect.top - dropdownHeight - margin
  }
  // 确保不超出视口
  top = Math.max(margin, Math.min(top, viewportHeight - dropdownHeight - margin))
  
  // 计算左侧位置（居中对齐触发按钮）
  let left = rect.left + rect.width / 2 - desiredWidth / 2
  
  // 关键：确保左侧和右侧都不超出视口
  if (left < margin) {
    left = margin
  } else if (left + desiredWidth > viewportWidth - margin) {
    left = viewportWidth - desiredWidth - margin
  }
  
  dropdownStyle.value = {
    position: 'fixed',
    top: `${top}px`,
    left: `${left}px`,
    width: `${desiredWidth}px`,
    maxWidth: `calc(100vw - ${margin * 2}px)`,
    zIndex: 9999
  }
}

// 选择预设
const selectPreset = (preset: PresetTheme) => {
  applyPresetTheme(preset.name)
  emit('update:modelValue', preset.color)
  emit('change', preset.color, preset)
  isOpen.value = false
}

// 处理自定义颜色
const handleCustomColor = () => {
  if (customColor.value) {
    applyTheme(customColor.value)
    emit('update:modelValue', customColor.value)
    emit('change', customColor.value)
    isOpen.value = false
  }
}

// 添加自定义主题
const handleAddCustomTheme = () => {
  if (!newThemeName.value || !newThemeColor.value) return

  const themeName = newThemeName.value
  const themeColor = newThemeColor.value

  try {
    // Try to get plugin instance
    const pluginInstance = instance?.appContext.config.globalProperties.$color

    if (pluginInstance && typeof pluginInstance.addCustomTheme === 'function') {
      pluginInstance.addCustomTheme({
        name: themeName,
        label: themeName,
        color: themeColor,
        custom: true
      })

      // Refresh presets
      presets.value = pluginInstance.getSortedPresets()

      // Reset inputs
      newThemeName.value = ''
      newThemeColor.value = '#1890ff'

      // Apply the new theme
      selectPreset({ name: themeName, label: themeName, color: themeColor, custom: true })
    } else {
      console.warn('[ThemePicker] Color plugin not found. Cannot add custom theme.')
    }
  } catch (error) {
    console.error('[ThemePicker] Failed to add custom theme:', error)
    alert(error instanceof Error ? error.message : 'Failed to add theme')
  }
}

// 删除自定义主题
const handleRemoveCustomTheme = (name: string) => {
  if (!confirm(t('theme.confirmRemove', `Remove theme "${name}"?`))) {
    return
  }

  try {
    // Try to get plugin instance
    const pluginInstance = instance?.appContext.config.globalProperties.$color

    if (pluginInstance && typeof pluginInstance.removeCustomTheme === 'function') {
      pluginInstance.removeCustomTheme(name)

      // Refresh presets
      presets.value = pluginInstance.getSortedPresets()

      // If current theme was removed, switch to default
      if (themeName.value === name) {
        applyPresetTheme('blue')
      }
    } else {
      console.warn('[ThemePicker] Color plugin not found. Cannot remove custom theme.')
    }
  } catch (error) {
    console.error('[ThemePicker] Failed to remove custom theme:', error)
    alert(error instanceof Error ? error.message : 'Failed to remove theme')
  }
}

// 点击外部关闭
const handleClickOutside = (event: MouseEvent) => {
  if (!pickerRef.value?.contains(event.target as Node)) {
    isOpen.value = false
  }
}

// 监听窗口调整
const handleResize = () => {
  if (isOpen.value) {
    updateDropdownPosition()
  }
}

onMounted(() => {
  // 恢复主题
  restoreTheme()
  
  // 监听事件
  document.addEventListener('click', handleClickOutside)
  window.addEventListener('resize', handleResize)
  window.addEventListener('scroll', handleResize)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  window.removeEventListener('resize', handleResize)
  window.removeEventListener('scroll', handleResize)
})

// 监听 modelValue 变化
watch(() => props.modelValue, (newValue) => {
  if (newValue && newValue !== primaryColor.value) {
    applyTheme(newValue)
  }
})
</script>

<style>
.ld-theme-picker {
  position: relative;
  display: inline-block;
}

.ld-theme-picker *,
.ld-theme-picker *::before,
.ld-theme-picker *::after {
  box-sizing: border-box;
}

.ld-theme-picker__trigger {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  padding: 0;
  border: none;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(10px);
  cursor: pointer;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.ld-theme-picker__trigger svg {
  display: block;
  transition: transform 0.2s;
}

.ld-theme-picker__trigger:hover {
  background: white;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  transform: translateY(-2px);
}

.ld-theme-picker__trigger:hover svg {
  transform: scale(1.1) rotate(-5deg);
}

.ld-theme-picker__trigger:active {
  transform: translateY(0);
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.12);
}

.ld-theme-picker__trigger:active svg {
  transform: scale(0.95);
}

.ld-theme-picker__dropdown {
  position: fixed;
  width: 296px;
  max-width: calc(100vw - 32px);
  max-height: 360px;
  background: white;
  border: 1px solid #e8e8e8;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08);
  overflow: hidden;
  overflow-x: hidden;
  transform-origin: top center;
  box-sizing: border-box;
}

/* Dropdown animations */
.ld-theme-picker-fade-enter-active {
  transition: all 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.ld-theme-picker-fade-leave-active {
  transition: all 0.2s cubic-bezier(0.4, 0, 1, 1);
}

.ld-theme-picker-fade-enter-from {
  opacity: 0;
  transform: scale(0.9) translateY(-8px);
}

.ld-theme-picker-fade-leave-to {
  opacity: 0;
  transform: scale(0.95) translateY(-4px);
}

.ld-theme-picker__search {
  padding: 12px;
  border-bottom: 1px solid #f0f0f0;
}

.ld-theme-picker__search-input {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  font-size: 14px;
  outline: none;
  transition: border-color 0.3s;
}

.ld-theme-picker__search-input:focus {
  border-color: #40a9ff;
}

.ld-theme-picker__content {
  max-height: 360px;
  overflow-y: auto;
  overflow-x: hidden;
  scrollbar-width: thin;
  scrollbar-color: #d9d9d9 transparent;
  box-sizing: border-box;
}

.ld-theme-picker__content::-webkit-scrollbar {
  width: 6px;
}

.ld-theme-picker__content::-webkit-scrollbar-track {
  background: transparent;
}

.ld-theme-picker__content::-webkit-scrollbar-thumb {
  background: #d9d9d9;
  border-radius: 3px;
}

.ld-theme-picker__content::-webkit-scrollbar-thumb:hover {
  background: #bfbfbf;
}

.ld-theme-picker__custom {
  padding: 12px;
  border-bottom: 1px solid #f0f0f0;
}

.ld-theme-picker__label {
  display: block;
  margin-bottom: 12px;
  font-size: 13px;
  color: #595959;
  font-weight: 500;
}

.ld-theme-picker__custom-input {
  display: flex;
  gap: 8px;
}

.ld-theme-picker__color-input {
  width: 40px;
  height: 32px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  cursor: pointer;
}

.ld-theme-picker__hex-input {
  flex: 1;
  padding: 6px 8px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  font-size: 14px;
  outline: none;
}

.ld-theme-picker__hex-input:focus {
  border-color: #40a9ff;
}

.ld-theme-picker__apply-btn {
  padding: 6px 12px;
  background: #1890ff;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 14px;
  cursor: pointer;
  transition: background 0.3s;
}

.ld-theme-picker__apply-btn:hover {
  background: #40a9ff;
}

.ld-theme-picker__presets {
  padding: 12px 16px 16px;
  box-sizing: border-box;
  overflow: hidden;
}

.ld-theme-picker__grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px 8px;
  align-items: start;
  box-sizing: border-box;
  width: 100%;
  max-width: 100%;
  overflow: hidden;
}

.ld-theme-picker__preset {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 5px;
  padding: 6px 3px;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  border: 2px solid transparent;
  min-width: 0;
  overflow: hidden;
}

.ld-theme-picker__preset:hover {
  background: #f7f7f7;
  transform: translateY(-1px);
}

.ld-theme-picker__preset.is-active {
  background: #f0f7ff;
  border-color: transparent;
}

.ld-theme-picker__preset-color {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  border: 2px solid transparent;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.12);
  transition: all 0.2s;
}

.ld-theme-picker__preset:hover .ld-theme-picker__preset-color {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.18);
}

.ld-theme-picker__preset.is-active .ld-theme-picker__preset-color {
  border-color: #1890ff;
  box-shadow: 0 2px 8px rgba(24, 144, 255, 0.35);
}

.ld-theme-picker__check {
  filter: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.3));
}

.ld-theme-picker__preset-label {
  font-size: 10.5px;
  color: #595959;
  text-align: center;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  width: 100%;
  line-height: 1.2;
  padding: 0 1px;
  word-break: keep-all;
}


/* 添加自定义主题样式 */
.ld-theme-picker__add-theme {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid #f0f0f0;
}

.ld-theme-picker__add-input {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.ld-theme-picker__name-input {
  flex: 1;
  min-width: 120px;
  padding: 6px 8px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  font-size: 14px;
  outline: none;
}

.ld-theme-picker__name-input:focus {
  border-color: #40a9ff;
}

.ld-theme-picker__add-btn {
  padding: 6px 12px;
  background: #52c41a;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 14px;
  cursor: pointer;
  transition: background 0.3s;
}

.ld-theme-picker__add-btn:hover:not(:disabled) {
  background: #73d13d;
}

.ld-theme-picker__add-btn:disabled {
  background: #d9d9d9;
  cursor: not-allowed;
}

/* 删除按钮样式 */
.ld-theme-picker__preset.is-custom {
  position: relative;
}

.ld-theme-picker__remove-btn {
  position: absolute;
  top: 4px;
  right: 4px;
  width: 20px;
  height: 20px;
  padding: 0;
  background: rgba(255, 77, 79, 0.9);
  color: white;
  border: none;
  border-radius: 50%;
  font-size: 16px;
  line-height: 1;
  cursor: pointer;
  opacity: 0;
  transition: opacity 0.2s, transform 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.ld-theme-picker__preset.is-custom:hover .ld-theme-picker__remove-btn {
  opacity: 1;
}

.ld-theme-picker__remove-btn:hover {
  background: #ff4d4f;
  transform: scale(1.1);
}

/* Responsive design for smaller screens */
@media (max-width: 360px) {
  .ld-theme-picker__dropdown {
    width: calc(100vw - 32px);
  }
  
  .ld-theme-picker__grid {
    grid-template-columns: repeat(3, 1fr);
  }
  
  .ld-theme-picker__preset {
    padding: 4px;
  }
  
  .ld-theme-picker__preset-color {
    width: 32px;
    height: 32px;
  }
}
</style>
