// packages/map/src/adapters/react/components/LDesignMapComponent.tsx
/**
 * LDesign地图React组件
 * 提供开箱即用的地图组件，支持完整的React生态集成
 */

import React, { useRef, useEffect, useCallback } from 'react'
import { useLDesignMap } from '../hooks/useLDesignMap'
import type { ReactMapProps } from '../types'
import './LDesignMapComponent.less'

/**
 * LDesign地图组件
 * 
 * @example
 * ```tsx
 * import React from 'react'
 * import { LDesignMapComponent } from '@ldesign/map/react'
 * 
 * function App() {
 *   const handleLoad = () => {
 *     console.log('地图加载完成')
 *   }
 * 
 *   const handleClick = (event) => {
 *     console.log('地图点击', event.lngLat)
 *   }
 * 
 *   return (
 *     <LDesignMapComponent
 *       options={{
 *         center: [116.404, 39.915],
 *         zoom: 10,
 *         accessToken: 'your-mapbox-token'
 *       }}
 *       markers={[
 *         {
 *           lngLat: [116.404, 39.915],
 *           popup: { content: '北京' }
 *         }
 *       ]}
 *       onLoad={handleLoad}
 *       onClick={handleClick}
 *       showDefaultControls
 *       showMapInfo
 *       height="500px"
 *     />
 *   )
 * }
 * ```
 */
export const LDesignMapComponent: React.FC<ReactMapProps> = ({
  options,
  markers = [],
  showDefaultControls = true,
  showMapInfo = false,
  height = '400px',
  width = '100%',
  className = '',
  style = {},
  onLoad,
  onClick,
  onMove,
  onZoom,
  onMarkerClick,
  onError,
  onUpdate,
  loadingContent,
  errorContent,
  controlsContent,
  infoContent
}) => {
  // 地图容器引用
  const mapContainer = useRef<HTMLDivElement>(null)

  // 使用地图Hook
  const mapInstance = useLDesignMap(mapContainer, options)

  const {
    map,
    isInitialized,
    isLoading,
    error,
    center,
    zoom,
    bearing,
    pitch,
    markers: currentMarkers,
    addMarker,
    removeMarker,
    clearMarkers
  } = mapInstance

  // 事件处理
  useEffect(() => {
    if (!map) return

    const handleMapLoad = () => onLoad?.()
    const handleMapClick = (event: any) => onClick?.(event)
    const handleMapMove = () => {
      onMove?.()
      onUpdate?.({ center, zoom, bearing, pitch })
    }
    const handleMapZoom = () => {
      onZoom?.()
      onUpdate?.({ center, zoom, bearing, pitch })
    }
    const handleMapError = (err: Error) => onError?.(err)

    // 注册事件监听器
    map.on('load', handleMapLoad)
    map.on('click', handleMapClick)
    map.on('move', handleMapMove)
    map.on('zoom', handleMapZoom)
    map.on('error', handleMapError)

    return () => {
      // 清理事件监听器
      map.off('load', handleMapLoad)
      map.off('click', handleMapClick)
      map.off('move', handleMapMove)
      map.off('zoom', handleMapZoom)
      map.off('error', handleMapError)
    }
  }, [map, onLoad, onClick, onMove, onZoom, onError, onUpdate, center, zoom, bearing, pitch])

  // 标记点同步
  useEffect(() => {
    if (!isInitialized) return

    // 清除现有标记点
    clearMarkers()

    // 添加新标记点
    markers.forEach(marker => {
      const id = addMarker(marker)
      
      // 如果有标记点点击事件，添加监听器
      if (onMarkerClick && map) {
        // 这里需要根据实际的标记点实现来添加点击事件
        // 暂时使用简化的实现
      }
    })
  }, [markers, isInitialized, addMarker, clearMarkers, onMarkerClick, map])

  // 控件方法
  const zoomIn = useCallback(() => {
    mapInstance.setZoom(zoom + 1)
  }, [mapInstance, zoom])

  const zoomOut = useCallback(() => {
    mapInstance.setZoom(zoom - 1)
  }, [mapInstance, zoom])

  const retry = useCallback(async () => {
    try {
      await mapInstance.initialize()
    } catch (err) {
      console.error('重试失败:', err)
    }
  }, [mapInstance])

  // 容器样式
  const containerStyle: React.CSSProperties = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    ...style
  }

  // 渲染加载状态
  const renderLoading = () => {
    if (loadingContent) {
      return loadingContent
    }

    return (
      <div className="ldesign-map-loading-overlay">
        <div className="ldesign-map-spinner" />
        <span className="ldesign-map-loading-text">地图加载中...</span>
      </div>
    )
  }

  // 渲染错误状态
  const renderError = () => {
    if (errorContent) {
      return errorContent(error!, retry)
    }

    return (
      <div className="ldesign-map-error-overlay">
        <div className="ldesign-map-error-content">
          <h3>地图加载失败</h3>
          <p>{error?.message}</p>
          <button onClick={retry} className="ldesign-map-retry-btn">
            重试
          </button>
        </div>
      </div>
    )
  }

  // 渲染控件
  const renderControls = () => {
    if (controlsContent) {
      return controlsContent(mapInstance)
    }

    if (!showDefaultControls) return null

    return (
      <div className="ldesign-map-default-controls">
        <button onClick={zoomIn} className="ldesign-map-control-btn">
          +
        </button>
        <button onClick={zoomOut} className="ldesign-map-control-btn">
          -
        </button>
      </div>
    )
  }

  // 渲染地图信息
  const renderInfo = () => {
    if (infoContent) {
      return infoContent({ center, zoom, bearing, pitch })
    }

    if (!showMapInfo) return null

    return (
      <div className="ldesign-map-info-content">
        <span>缩放: {zoom.toFixed(1)}</span>
        <span>中心: {center[0].toFixed(4)}, {center[1].toFixed(4)}</span>
      </div>
    )
  }

  return (
    <div
      className={`ldesign-map-container ${className} ${
        isLoading ? 'ldesign-map-loading' : ''
      } ${error ? 'ldesign-map-error' : ''}`}
      style={containerStyle}
    >
      {/* 地图容器 */}
      <div ref={mapContainer} className="ldesign-map-content" />

      {/* 加载状态 */}
      {isLoading && renderLoading()}

      {/* 错误状态 */}
      {error && renderError()}

      {/* 控件 */}
      {isInitialized && (
        <div className="ldesign-map-controls">
          {renderControls()}
        </div>
      )}

      {/* 地图信息 */}
      {isInitialized && showMapInfo && (
        <div className="ldesign-map-info">
          {renderInfo()}
        </div>
      )}
    </div>
  )
}

export default LDesignMapComponent

// packages/map/src/adapters/vue/components/LDesignMapComponent.vue
<!--
  LDesign地图Vue组件
  提供开箱即用的地图组件，支持插槽和事件
-->

<template>
  <div 
    ref="mapContainer" 
    class="ldesign-map-container"
    :class="{
      'ldesign-map-loading': isLoading,
      'ldesign-map-error': !!error
    }"
  >
    <!-- 加载状态 -->
    <div v-if="isLoading" class="ldesign-map-loading-overlay">
      <slot name="loading">
        <div class="ldesign-map-spinner"></div>
        <span class="ldesign-map-loading-text">地图加载中...</span>
      </slot>
    </div>

    <!-- 错误状态 -->
    <div v-if="error" class="ldesign-map-error-overlay">
      <slot name="error" :error="error">
        <div class="ldesign-map-error-content">
          <h3>地图加载失败</h3>
          <p>{{ error.message }}</p>
          <button @click="retry" class="ldesign-map-retry-btn">重试</button>
        </div>
      </slot>
    </div>

    <!-- 地图控件插槽 -->
    <div v-if="isInitialized" class="ldesign-map-controls">
      <slot name="controls" :map="map" :mapInstance="mapInstance">
        <!-- 默认控件 -->
        <div v-if="showDefaultControls" class="ldesign-map-default-controls">
          <button @click="zoomIn" class="ldesign-map-control-btn">+</button>
          <button @click="zoomOut" class="ldesign-map-control-btn">-</button>
        </div>
      </slot>
    </div>

    <!-- 地图信息插槽 -->
    <div v-if="isInitialized && showMapInfo" class="ldesign-map-info">
      <slot name="info" :center="center" :zoom="zoom" :bearing="bearing" :pitch="pitch">
        <div class="ldesign-map-info-content">
          <span>缩放: {{ zoom.toFixed(1) }}</span>
          <span>中心: {{ center[0].toFixed(4) }}, {{ center[1].toFixed(4) }}</span>
        </div>
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useLDesignMap } from '../composables/useLDesignMap'
import type { VueMapOptions, VueMapEvents } from '../types'
import type { MarkerOptions } from '../../../types'

// 定义组件名称
defineOptions({
  name: 'LDesignMapComponent'
})

/**
 * 组件属性定义
 */
interface Props {
  /** 地图配置选项 */
  options: VueMapOptions
  /** 标记点列表 */
  markers?: MarkerOptions[]
  /** 是否显示默认控件 */
  showDefaultControls?: boolean
  /** 是否显示地图信息 */
  showMapInfo?: boolean
  /** 地图高度 */
  height?: string | number
  /** 地图宽度 */
  width?: string | number
}

/**
 * 组件事件定义
 */
interface Emits {
  /** 地图加载完成 */
  load: []
  /** 地图点击 */
  click: [event: { lngLat: [number, number]; point: [number, number] }]
  /** 地图移动 */
  move: []
  /** 地图缩放 */
  zoom: []
  /** 标记点点击 */
  markerClick: [marker: MarkerOptions]
  /** 错误事件 */
  error: [error: Error]
  /** 地图状态更新 */
  update: [state: { center: [number, number]; zoom: number; bearing: number; pitch: number }]
}

// 定义props和emits
const props = withDefaults(defineProps<Props>(), {
  markers: () => [],
  showDefaultControls: true,
  showMapInfo: false,
  height: '400px',
  width: '100%'
})

const emit = defineEmits<Emits>()

// 地图容器引用
const mapContainer = ref<HTMLElement>()

// 事件处理器
const events: VueMapEvents = {
  onLoad: () => emit('load'),
  onClick: (event) => emit('click', event),
  onMove: () => {
    emit('move')
    emit('update', {
      center: center.value,
      zoom: zoom.value,
      bearing: bearing.value,
      pitch: pitch.value
    })
  },
  onZoom: () => {
    emit('zoom')
    emit('update', {
      center: center.value,
      zoom: zoom.value,
      bearing: bearing.value,
      pitch: pitch.value
    })
  },
  onMarkerClick: (marker) => emit('markerClick', marker),
  onError: (error) => emit('error', error)
}

// 使用地图组合式API
const mapInstance = useLDesignMap(mapContainer, props.options, events)

const {
  map,
  isInitialized,
  isLoading,
  error,
  center,
  zoom,
  bearing,
  pitch,
  markers,
  addMarker,
  removeMarker,
  clearMarkers
} = mapInstance

// 计算样式
const containerStyle = computed(() => ({
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
  width: typeof props.width === 'number' ? `${props.width}px` : props.width
}))

// 控件方法
const zoomIn = () => {
  if (map.value) {
    map.value.setZoom(zoom.value + 1)
  }
}

const zoomOut = () => {
  if (map.value) {
    map.value.setZoom(zoom.value - 1)
  }
}

const retry = async () => {
  try {
    await mapInstance.initialize()
  } catch (err) {
    console.error('重试失败:', err)
  }
}

// 监听标记点变化
watch(() => props.markers, (newMarkers, oldMarkers) => {
  if (!isInitialized.value) return

  // 清除旧标记点
  clearMarkers()

  // 添加新标记点
  newMarkers.forEach(marker => {
    addMarker(marker)
  })
}, { deep: true, immediate: true })

// 暴露给父组件的方法和属性
defineExpose({
  map,
  mapInstance,
  isInitialized,
  isLoading,
  error,
  center,
  zoom,
  bearing,
  pitch,
  markers,
  addMarker,
  removeMarker,
  clearMarkers,
  zoomIn,
  zoomOut,
  retry
})
</script>

<style lang="less" scoped>
.ldesign-map-container {
  position: relative;
  width: v-bind('containerStyle.width');
  height: v-bind('containerStyle.height');
  background-color: var(--ldesign-bg-color-container);
  border-radius: var(--ls-border-radius-base);
  overflow: hidden;
  box-shadow: var(--ldesign-shadow-1);

  &.ldesign-map-loading {
    pointer-events: none;
  }

  &.ldesign-map-error {
    border: 1px solid var(--ldesign-error-color);
  }
}

.ldesign-map-loading-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  z-index: 1000;

  .ldesign-map-spinner {
    width: 32px;
    height: 32px;
    border: 3px solid var(--ldesign-brand-color-3);
    border-top: 3px solid var(--ldesign-brand-color);
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: var(--ls-spacing-sm);
  }

  .ldesign-map-loading-text {
    color: var(--ldesign-text-color-secondary);
    font-size: var(--ls-font-size-sm);
  }
}

.ldesign-map-error-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: var(--ldesign-error-color-1);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;

  .ldesign-map-error-content {
    text-align: center;
    padding: var(--ls-padding-lg);

    h3 {
      color: var(--ldesign-error-color);
      margin: 0 0 var(--ls-spacing-sm) 0;
      font-size: var(--ls-font-size-lg);
    }

    p {
      color: var(--ldesign-text-color-secondary);
      margin: 0 0 var(--ls-spacing-base) 0;
      font-size: var(--ls-font-size-sm);
    }

    .ldesign-map-retry-btn {
      background-color: var(--ldesign-error-color);
      color: white;
      border: none;
      padding: var(--ls-padding-sm) var(--ls-padding-base);
      border-radius: var(--ls-border-radius-base);
      cursor: pointer;
      font-size: var(--ls-font-size-sm);
      transition: background-color 0.2s;

      &:hover {
        background-color: var(--ldesign-error-color-hover);
      }
    }
  }
}

.ldesign-map-controls {
  position: absolute;
  top: var(--ls-spacing-base);
  right: var(--ls-spacing-base);
  z-index: 100;

  .ldesign-map-default-controls {
    display: flex;
    flex-direction: column;
    gap: var(--ls-spacing-xs);

    .ldesign-map-control-btn {
      width: 32px;
      height: 32px;
      background-color: var(--ldesign-bg-color-component);
      border: 1px solid var(--ldesign-border-color);
      border-radius: var(--ls-border-radius-base);
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      font-size: var(--ls-font-size-lg);
      font-weight: bold;
      color: var(--ldesign-text-color-primary);
      transition: all 0.2s;
      box-shadow: var(--ldesign-shadow-1);

      &:hover {
        background-color: var(--ldesign-bg-color-component-hover);
        border-color: var(--ldesign-border-color-hover);
      }

      &:active {
        background-color: var(--ldesign-bg-color-component-active);
      }
    }
  }
}

.ldesign-map-info {
  position: absolute;
  bottom: var(--ls-spacing-base);
  left: var(--ls-spacing-base);
  z-index: 100;

  .ldesign-map-info-content {
    background-color: rgba(0, 0, 0, 0.7);
    color: white;
    padding: var(--ls-padding-xs) var(--ls-padding-sm);
    border-radius: var(--ls-border-radius-base);
    font-size: var(--ls-font-size-xs);
    display: flex;
    gap: var(--ls-spacing-sm);

    span {
      white-space: nowrap;
    }
  }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
