// library/picker/react/PickerComponent.tsx
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { Picker, PickerOption, PickerConfig } from '../core/Picker';

export interface PickerComponentProps {
  value?: string | number;
  options: PickerOption[];
  disabled?: boolean;
  visibleItems?: number;
  itemHeight?: number;
  panelHeight?: number;
  theme?: 'light' | 'dark' | 'auto';
  enable3d?: boolean;
  showMask?: boolean;
  momentum?: boolean;
  friction?: number;
  snapDuration?: number;
  resistance?: number;
  maxOverscroll?: number;
  searchable?: boolean;
  searchPlaceholder?: string;
  searchDebounce?: number;
  highlightMatch?: boolean;
  hapticFeedback?: boolean;
  hapticIntensity?: number;
  soundEffects?: boolean;
  soundVolume?: number;
  className?: string;
  style?: React.CSSProperties;
  onChange?: (value: string | number | undefined, option?: PickerOption) => void;
  onPick?: (value: string | number | undefined, option?: PickerOption, trigger: string) => void;
}

export interface PickerComponentRef {
  scrollToIndex: (index: number, animate?: boolean) => void;
  scrollToValue: (value: string | number, animate?: boolean) => void;
  getValue: () => string | number | undefined;
  setValue: (value: string | number | undefined, animate?: boolean) => void;
  setOptions: (options: PickerOption[]) => void;
  setDisabled: (disabled: boolean) => void;
}

const PickerComponent = forwardRef<PickerComponentRef, PickerComponentProps>((props, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const pickerInstanceRef = useRef<Picker | null>(null);
  const lastValueRef = useRef<string | number | undefined>(props.value);

  // 初始化Picker
  useEffect(() => {
    if (!containerRef.current) return;

    const config: PickerConfig = {
      options: props.options,
      value: props.value,
      disabled: props.disabled ?? false,
      visibleItems: props.visibleItems ?? 5,
      itemHeight: props.itemHeight ?? 36,
      panelHeight: props.panelHeight,
      theme: props.theme ?? 'light',
      enable3d: props.enable3d ?? false,
      showMask: props.showMask ?? true,
      momentum: props.momentum ?? true,
      friction: props.friction ?? 0.92,
      snapDuration: props.snapDuration ?? 300,
      resistance: props.resistance ?? 0.3,
      maxOverscroll: props.maxOverscroll,
      searchable: props.searchable ?? false,
      searchPlaceholder: props.searchPlaceholder ?? 'Search...',
      searchDebounce: props.searchDebounce ?? 300,
      highlightMatch: props.highlightMatch ?? true,
      hapticFeedback: props.hapticFeedback ?? false,
      hapticIntensity: props.hapticIntensity ?? 5,
      soundEffects: props.soundEffects ?? false,
      soundVolume: props.soundVolume ?? 0.3,
      onChange: (value, option) => {
        lastValueRef.current = value;
        props.onChange?.(value, option);
      },
      onPick: (value, option, trigger) => {
        props.onPick?.(value, option, trigger);
      }
    };

    pickerInstanceRef.current = new Picker(containerRef.current, config);

    return () => {
      pickerInstanceRef.current?.destroy();
      pickerInstanceRef.current = null;
    };
  }, []); // 只在mount时初始化

  // 处理value变化
  useEffect(() => {
    if (pickerInstanceRef.current && props.value !== lastValueRef.current) {
      pickerInstanceRef.current.setValue(props.value);
      lastValueRef.current = props.value;
    }
  }, [props.value]);

  // 处理options变化
  useEffect(() => {
    if (pickerInstanceRef.current) {
      pickerInstanceRef.current.setOptions(props.options);
    }
  }, [props.options]);

  // 处理disabled变化
  useEffect(() => {
    if (pickerInstanceRef.current) {
      pickerInstanceRef.current.setDisabled(props.disabled ?? false);
    }
  }, [props.disabled]);

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    scrollToIndex: (index: number, animate = true) => {
      pickerInstanceRef.current?.scrollToIndex(index, animate);
    },
    scrollToValue: (value: string | number, animate = true) => {
      pickerInstanceRef.current?.scrollToValue(value, animate);
    },
    getValue: () => {
      return pickerInstanceRef.current?.getValue();
    },
    setValue: (value: string | number | undefined, animate = true) => {
      pickerInstanceRef.current?.setValue(value, animate);
      lastValueRef.current = value;
    },
    setOptions: (options: PickerOption[]) => {
      pickerInstanceRef.current?.setOptions(options);
    },
    setDisabled: (disabled: boolean) => {
      pickerInstanceRef.current?.setDisabled(disabled);
    }
  }));

  return (
    <div 
      ref={containerRef} 
      className={`react-picker-wrapper ${props.className || ''}`}
      style={props.style}
    />
  );
});

PickerComponent.displayName = 'PickerComponent';

export default PickerComponent;

// library/picker/src/vue/PickerComponent.vue
<template>
  <div ref="containerRef" class="vue-picker-wrapper"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { Picker, PickerOption, PickerConfig } from '../core/Picker';

// Props定义
const props = withDefaults(defineProps<{
  modelValue?: string | number;
  options: PickerOption[];
  disabled?: boolean;
  visibleItems?: number;
  itemHeight?: number;
  panelHeight?: number;
  theme?: 'light' | 'dark' | 'auto';
  enable3d?: boolean;
  showMask?: boolean;
  momentum?: boolean;
  friction?: number;
  snapDuration?: number;
  resistance?: number;
  maxOverscroll?: number;
  searchable?: boolean;
  searchPlaceholder?: string;
  searchDebounce?: number;
  highlightMatch?: boolean;
  hapticFeedback?: boolean;
  hapticIntensity?: number;
  soundEffects?: boolean;
  soundVolume?: number;
}>(), {
  disabled: false,
  visibleItems: 5,
  itemHeight: 36,
  theme: 'light',
  enable3d: false,
  showMask: true,
  momentum: true,
  friction: 0.92,
  snapDuration: 300,
  resistance: 0.3,
  searchable: false,
  searchPlaceholder: '搜索...',
  searchDebounce: 300,
  highlightMatch: true,
  hapticFeedback: false,
  hapticIntensity: 5,
  soundEffects: false,
  soundVolume: 0.3
});

// Emits定义
const emit = defineEmits(['update:modelValue', 'change', 'pick']);

// Refs
const containerRef = ref<HTMLElement>();
let pickerInstance: Picker | null = null;

// 初始化Picker
const initPicker = () => {
  if (!containerRef.value) return;

  const config: PickerConfig = {
    options: props.options,
    value: props.modelValue,
    disabled: props.disabled,
    visibleItems: props.visibleItems,
    itemHeight: props.itemHeight,
    panelHeight: props.panelHeight,
    theme: props.theme,
    enable3d: props.enable3d,
    showMask: props.showMask,
    momentum: props.momentum,
    friction: props.friction,
    snapDuration: props.snapDuration,
    resistance: props.resistance,
    maxOverscroll: props.maxOverscroll,
    searchable: props.searchable,
    searchPlaceholder: props.searchPlaceholder,
    searchDebounce: props.searchDebounce,
    highlightMatch: props.highlightMatch,
    hapticFeedback: props.hapticFeedback,
    hapticIntensity: props.hapticIntensity,
    soundEffects: props.soundEffects,
    soundVolume: props.soundVolume,
    onChange: (value, option) => {
      emit('update:modelValue', value);
      emit('change', value, option);
    },
    onPick: (value, option, trigger) => {
      emit('pick', value, option, trigger);
    }
  };

  pickerInstance = new Picker(containerRef.value, config);
};

// 生命周期
onMounted(() => {
  initPicker();
});

onUnmounted(() => {
  if (pickerInstance) {
    pickerInstance.destroy();
    pickerInstance = null;
  }
});

// 监听props变化
watch(() => props.modelValue, (newValue) => {
  if (pickerInstance && pickerInstance.getValue() !== newValue) {
    pickerInstance.setValue(newValue);
  }
});

watch(() => props.options, (newOptions) => {
  if (pickerInstance) {
    pickerInstance.setOptions(newOptions);
  }
}, { deep: true });

watch(() => props.disabled, (newDisabled) => {
  if (pickerInstance) {
    pickerInstance.setDisabled(newDisabled);
  }
});

// 暴露方法
defineExpose({
  scrollToIndex: (index: number, animate = true) => {
    pickerInstance?.scrollToIndex(index, animate);
  },
  scrollToValue: (value: string | number, animate = true) => {
    pickerInstance?.scrollToValue(value, animate);
  },
  getValue: () => {
    return pickerInstance?.getValue();
  },
  setValue: (value: string | number | undefined, animate = true) => {
    pickerInstance?.setValue(value, animate);
  }
});
</script>

<style scoped>
.vue-picker-wrapper {
  display: inline-block;
}
</style>
